name: release-to-dockerhub

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tag to be used for the built image (this should be some version number that somewhat matches the MobileCoin release version). This tag is used when publishing to DockerHub' 
        required: true
        default: 
  #push:
  #  branches:
  #    - "main"
  #pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY_IMAGE: eranrund/temp-mobilecoind

jobs:
  docker:
    #runs-on: [ "ubuntu-latest-m" ]
    runs-on: [ "ubuntu-latest" ]
    strategy:
      matrix:
        network: ["test", "prod"]
    steps:
      - name: Debug
        run: |
          echo "ref is ${{ github.ref_name }}"

#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          submodules: recursive
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ env.REGISTRY_IMAGE }}-${{ matrix.network }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          #tags: ${{ steps.meta.outputs.tags }}
#          tags: ${{ github.ref_name }}
#          labels: ${{ steps.meta.outputs.labels }}
#          build-args: |
#            NETWORK=${{ matrix.network }}.mobilecoin.com
